apiVersion: batch/v1
kind: Job
metadata:
  name: condaenv-exporter
spec:
  template:
    spec:
      containers:
      - name: condaenv-exporter
        image: registry.zyn.kr:6543/dataon.kr/condaenv-exporter:0.2
        volumeMounts:
        - name: conda-pubenvs
          mountPath: /opt/conda/pubenvs
        - name: conda-usrenvs
          mountPath: /opt/conda/usrenvs
        env:
        - name: EXPORTMODE
          value: $EXPORTMODE
        - name: NB_USER
          value: $NB_USER
        - name: NB_UID
          value: $NB_UID
        - name: NB_GID
          value: $NB_GID
        - name: SRCENVNAME
          value: $SRCENVNAME
        - name: DSTENVNAME
          value: $DSTENVNAME
        - name: WETRUNARGS
          value: $WETRUNARGS
      volumes:
      - name: conda-pubenvs
        nfs:
          server: ipa-k1805.zyn.kr
          path: /home/xo/miniconda3/tmp
      - name: conda-usrenvs
        nfs:
          server: ipa-k1805.zyn.kr
          path: /home/xo/miniconda3/envs
      restartPolicy: Never
