# Copyright (c) Jupyter Development Team.
# Copyright (c) Seungkyun Hong. <nah@kakao.com>
# Distributed under the terms of the Modified BSD License.

ARG ROOT_CONTAINER=inscite/base-conda:0.4-cuda10.1
ARG BASE_CONTAINER=$ROOT_CONTAINER
FROM $BASE_CONTAINER

LABEL maintainer="Seungkyun Hong <nah@kakao.com>"

USER root

# Install only gcc 4.8 for some compatibility issue
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    gcc-4.8 g++-4.8 \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# gcc alternatives set-up
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 \
 && update-alternatives --config gcc

USER $NB_UID
WORKDIR $HOME
