# Copyright (c) Jupyter Development Team.
# Copyright (c) Seungkyun Hong. <nah@kakao.com>
# Distributed under the terms of the Modified BSD License.

# Ubuntu 18.04 (bionic) + NVIDIA CUDA 10.2 with runtime libraries (cuDNN/NCCL) -> base-jupyterlab:0.4-cuda10.2
# https://hub.docker.com/r/nvidia/cuda/tags?name=10.2-cudnn7-runtime-ubuntu18.04
# OS/ARCH: linux/amd64
ARG ROOT_CONTAINER=inscite/base-conda:0.4-cuda10.2
ARG BASE_CONTAINER=$ROOT_CONTAINER
FROM $BASE_CONTAINER

LABEL maintainer="Seungkyun Hong <nah@kakao.com>"

# Install Jupyter Notebook, Lab, and Hub
# Generate a notebook server config
# Cleanup temporary files
# Correct permissions
# Do all this in a single RUN command to avoid duplicating all of the
# files across image layers when the permissions change
# refer this for ipyparall enable: https://ipyparallel.readthedocs.io/en/latest/index.html?highlight=serverextension#installing-ipython-parallel
RUN conda install --quiet --yes \
    'notebook=6.0.3' \
    'jupyterhub=1.1.0' \
    'jupyterlab=2.1.5' \
    'nb_conda_kernels' && \
    conda clean --all -f -y && \
    npm cache clean --force && \
    jupyter notebook --generate-config && \
    rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
    rm -rf /home/$NB_USER/.cache/yarn && \
    pip install -q ipyparallel && \
    ipython profile create --parallel --profile=mpi && \
    echo "c.IPClusterStart.controller_launcher_class = 'MPIControllerLauncher'" \
    >> /home/$NB_USER/.ipython/profile_mpi/ipcluster_config.py && \
    echo "colorscheme delek" >> /home/$NB_USER/.vimrc && \
    conda init bash && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

EXPOSE 8888

# Configure container startup
ENTRYPOINT ["tini", "-g", "--"]
CMD ["start-notebook.sh"]

# Copy local files as late as possible to avoid cache busting
COPY start.sh start-notebook.sh start-singleuser.sh /usr/local/bin/
COPY jupyter_notebook_config.py /etc/jupyter/

# Fix permissions on /etc/jupyter as root
USER root
RUN fix-permissions /etc/jupyter/

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID
WORKDIR $HOME
